"""gRPC client for crias-agent with reconnect backoff and status cache.

Async-safe for concurrent RPCs.
"""

from __future__ import annotations

import asyncio
import logging
import time
from collections.abc import AsyncIterator
from typing import Any

import grpc
from grpc import aio as grpc_aio

# Proto stubs generated by grpc_tools.protoc (see README).
try:
    from .grpc_gen import crias_pb2, crias_pb2_grpc
except ImportError as exc:
    # Dev fallback when proto not generated.
    raise ImportError(
        "Código protobuf não gerado. Execute:\n"
        "  cd discord-bot && python -m grpc_tools.protoc "
        "-I ../discord-agent/proto --python_out=grpc_gen "
        "--grpc_python_out=grpc_gen ../discord-agent/proto/crias.proto"
    ) from exc


logger = logging.getLogger(__name__)


class AgentClientError(Exception):
    """Agent communication error."""


# Default unary RPC timeout (seconds).
DEFAULT_RPC_TIMEOUT: float = 10.0


def _is_localhost(host: str) -> bool:
    """Return True if host resolves to localhost."""
    # strip scheme
    clean = host
    for scheme in ("https://", "http://"):
        if clean.startswith(scheme):
            clean = clean[len(scheme) :]
            break
    # strip port
    clean = clean.split(":", 1)[0].rstrip("/")
    return clean in ("127.0.0.1", "localhost", "::1", "[::1]")


class AgentClient:
    """Async gRPC client for crias-agent, safe for concurrent RPCs."""

    def __init__(
        self,
        host: str,
        token: str,
        max_reconnect_delay: int = 60,
        *,
        tls_ca_path: str | None = None,
        use_tls: bool = False,
    ) -> None:
        self.host = host
        self.token = token
        self.max_reconnect_delay = max_reconnect_delay
        self._tls_ca_path = tls_ca_path
        self._force_tls = use_tls

        self._channel: grpc_aio.Channel | None = None
        self._stub: crias_pb2_grpc.ServerControlStub | None = None
        self._event_stub: crias_pb2_grpc.EventBusStub | None = None

        # Serializes concurrent connect() calls from multiple coroutines.
        self._connect_lock: asyncio.Lock = asyncio.Lock()

        # Signals close() to break connect() retry loop.
        self._closing: asyncio.Event = asyncio.Event()

        # GetStatus cache.
        self._status_cache: tuple[crias_pb2.StatusResponse, float] | None = None
        self._status_cache_ttl: float = 15.0  # seconds

    async def connect(self) -> None:
        """Connect with exponential backoff up to 60s. Closes stale channel first to avoid FD leak."""
        async with self._connect_lock:
            # Double-check after lock (another coroutine may have connected).
            if self._stub is not None and self._event_stub is not None:
                return

            delay = 1.0
            while True:
                # Abort retry if close() was called.
                if self._closing.is_set():
                    return

                # Close stale channel to avoid resource leak.
                if self._channel is not None:
                    try:
                        await self._channel.close()
                    except Exception:
                        pass
                    self._channel = None
                    self._stub = None
                    self._event_stub = None

                try:
                    self._channel = self._create_channel()

                    # Wait for channel ready (5s timeout).
                    await asyncio.wait_for(self._channel.channel_ready(), timeout=5.0)

                    self._stub = crias_pb2_grpc.ServerControlStub(self._channel)
                    self._event_stub = crias_pb2_grpc.EventBusStub(self._channel)
                    logger.info("conectado ao agente em %s", self.host)
                    return
                except (grpc.RpcError, TimeoutError, OSError) as e:
                    logger.warning("connect falhou (próxima tentativa em %.1fs): %s", delay, e)
                    # Close partially created channel to avoid leak.
                    if self._channel is not None:
                        try:
                            await self._channel.close()
                        except Exception:
                            pass
                        self._channel = None
                    # Wait interruptible by _closing event.
                    try:
                        await asyncio.wait_for(
                            self._closing.wait(), timeout=min(delay, self.max_reconnect_delay)
                        )
                        return  # closing setou, aborta
                    except TimeoutError:
                        pass
                    delay *= 2

    def _create_channel(self) -> grpc_aio.Channel:
        """Create gRPC channel. TLS required for non-localhost to avoid cleartext token leak."""
        target = self.host
        # Determine scheme and clean target.
        if target.startswith("https://"):
            target = target[len("https://") :]
            use_tls = True
        elif target.startswith("http://"):
            target = target[len("http://") :]
            use_tls = False
        else:
            use_tls = self._force_tls

        is_local = _is_localhost(target)

        if not use_tls and not is_local:
            # Insecure channel would leak the token in cleartext.
            raise AgentClientError(
                f"Canal inseguro não permitido para host não-localhost: {target}. "
                "Use HTTPS (https://...) ou configure CRIAS_AGENT_USE_TLS=true."
            )

        if use_tls:
            if self._tls_ca_path:
                with open(self._tls_ca_path, "rb") as f:
                    creds = grpc_aio.ssl_channel_credentials(root_certificates=f.read())
            else:
                creds = grpc_aio.ssl_channel_credentials()
            return grpc_aio.secure_channel(
                target,
                creds,
                options=[
                    ("grpc.max_receive_message_length", 1 * 1024 * 1024),
                    # keepalive to detect dead connections.
                    ("grpc.keepalive_time_ms", 30000),
                    ("grpc.keepalive_timeout_ms", 10000),
                ],
            )

        # localhost: insecure channel.
        return grpc_aio.insecure_channel(
            target,
            options=[("grpc.max_receive_message_length", 1 * 1024 * 1024)],
        )

    async def close(self) -> None:
        """Close gRPC channel with 5s timeout to avoid hang."""
        self._closing.set()  # signal connect() to abort
        async with self._connect_lock:
            if self._channel is not None:
                try:
                    await asyncio.wait_for(self._channel.close(), timeout=5.0)
                except TimeoutError:
                    logger.warning("timeout ao fechar canal gRPC (5s)")
                except Exception as e:
                    logger.warning("erro ao fechar canal gRPC: %s", e)
                self._channel = None
                self._stub = None
                self._event_stub = None

    def _metadata(self) -> list[tuple[str, str]]:
        return [("x-api-token", self.token)]

    async def _ensure_connected(self) -> None:
        if self._stub is None or self._event_stub is None:
            await self.connect()

    async def _handle_rpc_error(self, e: grpc.RpcError) -> None:
        """Reset stub/channel on persistent RPC failures so the next call reconnects.

        Only resets when the error suggests the channel itself is broken
        (UNAVAILABLE / UNKNOWN); transient per-RPC errors (DEADLINE_EXCEEDED,
        PERMISSION_DENIED, ...) leave the channel intact.
        """
        code_fn = getattr(e, "code", None)
        code = code_fn() if callable(code_fn) else None
        if code not in (grpc.StatusCode.UNAVAILABLE, grpc.StatusCode.UNKNOWN):
            return
        logger.warning(
            "RPC falhou com %s — resetando canal gRPC para forçar reconexão", code
        )
        self._stub = None
        self._event_stub = None
        # Drop cached status so we don't serve stale data after reconnect.
        self._status_cache = None
        if self._channel is not None:
            try:
                await self._channel.close()
            except Exception as close_err:
                logger.debug("erro ao fechar canal gRPC após falha: %s", close_err)
            self._channel = None

    # --- ServerControl RPCs ---

    async def start_server(self) -> dict[str, Any]:
        await self._ensure_connected()
        if self._stub is None:
            raise AgentClientError("não conectado ao agente")
        try:
            resp = await self._stub.StartServer(
                crias_pb2.StartRequest(),
                metadata=self._metadata(),
                timeout=DEFAULT_RPC_TIMEOUT,
            )
            return {"ok": resp.ok, "message": resp.message, "service": resp.service_name}
        except grpc.RpcError as e:
            await self._handle_rpc_error(e)
            raise AgentClientError(f"StartServer falhou: {e}") from e

    async def stop_server(self) -> dict[str, Any]:
        await self._ensure_connected()
        if self._stub is None:
            raise AgentClientError("não conectado ao agente")
        try:
            resp = await self._stub.StopServer(
                crias_pb2.StopRequest(),
                metadata=self._metadata(),
                timeout=DEFAULT_RPC_TIMEOUT,
            )
            return {"ok": resp.ok, "message": resp.message, "service": resp.service_name}
        except grpc.RpcError as e:
            await self._handle_rpc_error(e)
            raise AgentClientError(f"StopServer falhou: {e}") from e

    async def restart_server(self) -> dict[str, Any]:
        await self._ensure_connected()
        if self._stub is None:
            raise AgentClientError("não conectado ao agente")
        try:
            resp = await self._stub.RestartServer(
                crias_pb2.RestartRequest(),
                metadata=self._metadata(),
                timeout=DEFAULT_RPC_TIMEOUT,
            )
            return {"ok": resp.ok, "message": resp.message, "service": resp.service_name}
        except grpc.RpcError as e:
            await self._handle_rpc_error(e)
            raise AgentClientError(f"RestartServer falhou: {e}") from e

    async def get_status(
        self, use_cache: bool = True, cache_ttl: float | None = None
    ) -> dict[str, Any]:
        """Return server status. Uses short cache by default."""
        if use_cache and self._status_cache is not None:
            cached_resp, cached_at = self._status_cache
            ttl = cache_ttl if cache_ttl is not None else self._status_cache_ttl
            if time.monotonic() - cached_at < ttl:
                return _status_to_dict(cached_resp)

        await self._ensure_connected()
        if self._stub is None:
            raise AgentClientError("não conectado ao agente")
        try:
            resp = await self._stub.GetStatus(
                crias_pb2.GetStatusRequest(),
                metadata=self._metadata(),
                timeout=DEFAULT_RPC_TIMEOUT,
            )
            self._status_cache = (resp, time.monotonic())
            return _status_to_dict(resp)
        except grpc.RpcError as e:
            await self._handle_rpc_error(e)
            raise AgentClientError(f"GetStatus falhou: {e}") from e

    async def get_health(self) -> dict[str, Any]:
        await self._ensure_connected()
        if self._stub is None:
            raise AgentClientError("não conectado ao agente")
        try:
            resp = await self._stub.GetHealth(
                crias_pb2.GetHealthRequest(),
                metadata=self._metadata(),
                timeout=DEFAULT_RPC_TIMEOUT,
            )
            return {
                "healthy": resp.healthy,
                "service": resp.service_name,
                "port_listening": resp.port_listening,
                "port": resp.port,
                "rcon_responsive": resp.rcon_responsive,
                "message": resp.message,
            }
        except grpc.RpcError as e:
            await self._handle_rpc_error(e)
            raise AgentClientError(f"GetHealth falhou: {e}") from e

    async def send_rcon_command(self, command: str) -> dict[str, Any]:
        await self._ensure_connected()
        if self._stub is None:
            raise AgentClientError("não conectado ao agente")
        try:
            resp = await self._stub.SendRconCommand(
                crias_pb2.SendRconCommandRequest(command=command),
                metadata=self._metadata(),
                timeout=DEFAULT_RPC_TIMEOUT,
            )
            return {"ok": resp.ok, "output": resp.output, "error": resp.error}
        except grpc.RpcError as e:
            await self._handle_rpc_error(e)
            raise AgentClientError(f"SendRconCommand falhou: {e}") from e

    async def stream_console(self, tail_lines: int = 50) -> AsyncIterator[str]:
        """Stream console output indefinitely until caller cancels."""
        await self._ensure_connected()
        if self._stub is None:
            raise AgentClientError("não conectado ao agente")
        try:
            stream = self._stub.StreamConsole(
                crias_pb2.StreamConsoleRequest(tail_lines=tail_lines),
                metadata=self._metadata(),
            )
            async for line in stream:
                yield line.line
        except grpc.RpcError as e:
            await self._handle_rpc_error(e)
            raise AgentClientError(f"StreamConsole falhou: {e}") from e

    # --- EventBus RPCs ---

    async def subscribe_events(
        self, event_types: list[str] | None = None
    ) -> AsyncIterator[dict[str, Any]]:
        """Subscribe to agent events indefinitely."""
        await self._ensure_connected()
        assert self._event_stub is not None
        try:
            req = crias_pb2.SubscribeEventsRequest()
            if event_types:
                req.event_types.extend(event_types)
            stream = self._event_stub.SubscribeEvents(req, metadata=self._metadata())
            async for ev in stream:
                yield {
                    "event_id": ev.event_id,
                    "event_type": ev.event_type,
                    "timestamp": ev.timestamp_unix,
                    "service": ev.service_name,
                    "stack": ev.stack,
                    "metadata": dict(ev.metadata),
                }
        except grpc.RpcError as e:
            await self._handle_rpc_error(e)
            raise AgentClientError(f"SubscribeEvents falhou: {e}") from e


def _status_to_dict(resp: crias_pb2.StatusResponse) -> dict[str, Any]:
    return {
        "service_active": resp.service_active,
        "service_name": resp.service_name,
        "stack": resp.stack,
        "player_count": resp.player_count,
        "players": list(resp.players),
        "max_players": resp.max_players,
        "uptime_seconds": resp.uptime_seconds,
        "hardware_tier": resp.hardware_tier,
        "memory_used_mb": resp.memory_used_mb,
        "memory_max_mb": resp.memory_max_mb,
        "version": resp.version,
    }
