// Package config loads and validates /etc/crias/agent.yaml.
package config

import (
	"fmt"
	"os"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

// authTokenRegex validates the auth token format: 64 lowercase hex chars (256 bits of entropy), as generated by `openssl rand -hex 32`.
var authTokenRegex = regexp.MustCompile(`^[0-9a-f]{64}$`)

// serviceNameRegex validates systemd service names against a safe character set.
var serviceNameRegex = regexp.MustCompile(`^[a-zA-Z0-9_.@-]+$`)

// Config is the root structure of agent.yaml.
type Config struct {
	Agent    AgentConfig    `yaml:"agent"`
	Server   ServerConfig   `yaml:"server"`
	Features FeaturesConfig `yaml:"features"`
}

// AgentConfig controls the gRPC listener.
type AgentConfig struct {
	BindAddress string `yaml:"bind_address"`
	Port        int    `yaml:"port"`
	AuthToken   string `yaml:"auth_token"`
	// TLSCert and TLSKey enable TLS/mTLS on the gRPC server.
	// Required when bind_address != 127.0.0.1/::1/localhost.
	TLSCert string `yaml:"tls_cert"`
	TLSKey  string `yaml:"tls_key"`
}

// ServerConfig points to the active stack and how to delegate commands.
type ServerConfig struct {
	Stack         string     `yaml:"stack"`          // "minecraft" | "terraria"
	ServiceName   string     `yaml:"service_name"`   // e.g. "minecraft"
	ManagerScript string     `yaml:"manager_script"` // /opt/minecraft-server/mc-manager.sh
	ServerDir     string     `yaml:"server_dir"`     // /opt/minecraft-server
	ServerPort    int        `yaml:"server_port"`    // game server port (25565 MC, 7777 TT)
	HardwareTier  string     `yaml:"hardware_tier"`  // LOW/MID/HIGH (mirrors install.sh)
	RCON          RCONConfig `yaml:"rcon"`
}

// RCONConfig enables player queries and say.
type RCONConfig struct {
	Enabled  bool   `yaml:"enabled"`
	Host     string `yaml:"host"`
	Port     int    `yaml:"port"`
	Password string `yaml:"password"`
}

// FeaturesConfig controls optional agent features.
type FeaturesConfig struct {
	AutoShutdown AutoShutdownConfig `yaml:"auto_shutdown"`
	HealthCheck  HealthCheckConfig  `yaml:"health_check"`
}

// AutoShutdownConfig: when enabled, stops the server after N empty minutes.
type AutoShutdownConfig struct {
	Enabled      bool `yaml:"enabled"`
	EmptyMinutes int  `yaml:"empty_minutes"`
}

// HealthCheckConfig: passive health check at N-second intervals (does not restart).
type HealthCheckConfig struct {
	IntervalSeconds int  `yaml:"interval_seconds"`
	Passive         bool `yaml:"passive"`
}

// Load reads and parses agent.yaml at the given path.
// Returns an error if the file is missing, invalid YAML, or contains
// insecure configuration (weak token, non-loopback bind without TLS, etc.).
func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("ler %s: %w", path, err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse yaml %s: %w", path, err)
	}

	// Sane defaults for required fields.
	if cfg.Agent.BindAddress == "" {
		cfg.Agent.BindAddress = "127.0.0.1"
	}
	if cfg.Agent.Port == 0 {
		cfg.Agent.Port = 8473
	}
	if cfg.Features.AutoShutdown.EmptyMinutes == 0 {
		cfg.Features.AutoShutdown.EmptyMinutes = 30
	}
	if cfg.Features.HealthCheck.IntervalSeconds == 0 {
		cfg.Features.HealthCheck.IntervalSeconds = 300
	}
	if cfg.Server.Stack == "" {
		cfg.Server.Stack = "minecraft"
	}

	// Validate auth_token format (64 hex chars); rejects placeholders and weak tokens.
	if cfg.Agent.AuthToken == "" {
		return nil, fmt.Errorf("agent.auth_token não pode ser vazio")
	}
	if cfg.Agent.AuthToken == "CHANGE_ME_TO_RANDOM_64_HEX_CHARS" {
		return nil, fmt.Errorf("agent.auth_token ainda é o placeholder — gere com: openssl rand -hex 32")
	}
	if !authTokenRegex.MatchString(cfg.Agent.AuthToken) {
		return nil, fmt.Errorf("agent.auth_token deve ter 64 caracteres hex minúsculos (gerado por `openssl rand -hex 32`)")
	}

	// Validate service_name against a safe character set.
	if cfg.Server.ServiceName == "" {
		return nil, fmt.Errorf("server.service_name não pode ser vazio")
	}
	if !serviceNameRegex.MatchString(cfg.Server.ServiceName) {
		return nil, fmt.Errorf("server.service_name %q contém caracteres inválidos (use apenas [a-zA-Z0-9_.@-])", cfg.Server.ServiceName)
	}

	// Non-loopback bind requires TLS (defense-in-depth against cleartext token exposure).
	if !isLoopback(cfg.Agent.BindAddress) {
		if cfg.Agent.TLSCert == "" || cfg.Agent.TLSKey == "" {
			return nil, fmt.Errorf(
				"agent.bind_address %q requer TLS (configure tls_cert e tls_key, ou use 127.0.0.1)",
				cfg.Agent.BindAddress,
			)
		}
	}

	// Reject placeholder RCON passwords.
	if cfg.Server.RCON.Enabled {
		if cfg.Server.RCON.Password == "" {
			return nil, fmt.Errorf("server.rcon.password não pode ser vazio quando rcon.enabled=true")
		}
		if strings.HasPrefix(cfg.Server.RCON.Password, "CHANGE_ME_") {
			return nil, fmt.Errorf("server.rcon.password ainda é o placeholder — defina o password real de server.properties")
		}
	}

	// Validate RCON host/port when enabled.
	if cfg.Server.RCON.Enabled {
		if cfg.Server.RCON.Host == "" {
			cfg.Server.RCON.Host = "127.0.0.1"
		}
		if cfg.Server.RCON.Port == 0 {
			return nil, fmt.Errorf("server.rcon.port não pode ser 0 quando rcon.enabled=true")
		}
	}

	return &cfg, nil
}

// isLoopback returns true for 127.0.0.1, ::1, or localhost.
func isLoopback(addr string) bool {
	switch addr {
	case "127.0.0.1", "::1", "localhost":
		return true
	default:
		return false
	}
}

// DefaultConfigPath returns the default agent.yaml path (CRIAS_AGENT_CONFIG env var overrides).
func DefaultConfigPath() string {
	if p := os.Getenv("CRIAS_AGENT_CONFIG"); p != "" {
		return p
	}
	return "/etc/crias/agent.yaml"
}
